name: Default
description: godot-solana-sdk issue form
title: ""
labels: []
projects: []
assignees:
  - Virus-Axel
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What can be improved? Describe the issue please.
      placeholder: Description here
    validations:
      required: true
  - type: textarea
    id: improvements
    attributes:
      label: Suggested Improvements
      description: Optionally describe how you think the SDK can be improved.
      placeholder: Your oppinion matters.
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Extra Information
      description: Optionally add extra information you think can be helpful.
      placeholder: Versions for example and OS.
    validations:
      required: false
